### ISSUE TITLE
English text instead of russia text

### ISSUE THREAD

**Issue by MandiYang** [COOLIRON2311/CobraAV#1]
Read the title

**Comment by MandiYang** [comment]
Also, the /usr/bin/cobra symlink is broken

**Comment by COOLIRON2311** [comment]
> Also, the /usr/bin/cobra symlink is broken

Symlink is fixed now. English language support is planned for future release.

**Comment by josephjoguts** [comment]
so where is english support?

**Comment by MandiYang** [comment]
@josephjoguts English support seems to not have come out yet but @COOLIRON2311 said it will come in future releases, just be more patient.

**Comment by COOLIRON2311** [comment]
@MandiYang @josephjoguts 
English translation has finally been added in [1.2 release](https://github.com/COOLIRON2311/CobraAV/releases/tag/1.2)

We're sorry that it took us so long. CobraAV has been our course work at [Southern Federal University](https://sfedu.ru) and we really enjoyed it! Unfortunately, we don't have enough time now to support it the way we would want to. But it is your feedback that really motivates us to release new updates!
